// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "gostar/prevention/category/pkg/endpoint"
	pb "gostar/prevention/category/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	getByName grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.CategoryServer {
	return &grpcServer{getByName: makeGetByNameHandler(endpoints, options["GetByName"])}
}
