// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "gostar/prevention/product/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	CreateProductEndpoint endpoint.Endpoint
	GetProductEndpoint    endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.ProductService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		CreateProductEndpoint: MakeCreateProductEndpoint(s),
		GetProductEndpoint:    MakeGetProductEndpoint(s),
	}
	for _, m := range mdw["CreateProduct"] {
		eps.CreateProductEndpoint = m(eps.CreateProductEndpoint)
	}
	for _, m := range mdw["GetProduct"] {
		eps.GetProductEndpoint = m(eps.GetProductEndpoint)
	}
	return eps
}
